
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-server"
  config.vm.box_version = "1809.0.1910"
  config.vm.hostname = "iis"
  config.vm.synced_folder "../scripts", "C:\\Install"
  # Configure VM settings using vboxmanage flags
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--vram", "128", "--cpus", "4", "--memory", "4096"]
  end
  config.vm.network "forwarded_port", guest: 443, host: 44443
  config.vm.network "forwarded_port", guest: 80, host: 4480
  # Bootstrap the VM
  config.vm.provision "shell", name: "Bootstrap", inline: ". C:\\Install\\BootstrapFunctions.ps1; Install-Code"
  config.vm.provision "shell", name: "DeployIIS",  inline: "C:\\Install\\DeployIIS.ps1"
end
