Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "jenkins"
    # Configure VM settings using vboxmanage flags
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "jenkins", "--vram", "128", "--cpus", "2", "--memory", "2048"]
    end
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.provision "shell", name: "Install Jenkins", inline: "/vagrant/jenkins.sh"
  end